#! /usr/bin/bash

set -e

die() { echo >&2 "!! $*"; exit 1; }

MOLYUU_CONTROLLER_PATH="/usr/bin/molyuuctl"

if [[ ! -f "$MOLYUU_CONTROLLER_PATH" ]]; then
    die "Molyuu controller not found at $MOLYUU_CONTROLLER_PATH"
fi

if [[ $EUID != 0 ]]; then
    exec pkexec "$(realpath $0)" "$1"
fi

"$MOLYUU_CONTROLLER_PATH" session set-oneshot "$1"
"$MOLYUU_CONTROLLER_PATH" login now